import pyautogui
import time

time.sleep(2)
pyautogui.write("Ngày ngủ đêm cày air", interval = 2)
pyautogui.press("enter")
pyautogui.write("Mọi người ngủ hết rồi à", interval = 2)
pyautogui.press("enter")
pyautogui.write("E mới vào ạ chào mọi người", interval = 2)
pyautogui.press("enter")
pyautogui.write("chát để lên level mỏi hết tay", interval = 2)
pyautogui.press("enter")
pyautogui.write("lâu lên level 7 quá", interval = 2)
pyautogui.press("enter")
pyautogui.write("Ngày ngủ đêm cày air", interval = 2)
pyautogui.press("enter")
pyautogui.write("Mọi người ngủ hết rồi à", interval = 2)
pyautogui.press("enter")
pyautogui.write("E mới vào ạ chào mọi người", interval = 2)
pyautogui.press("enter")
pyautogui.write("chát để lên level mỏi hết tay", interval = 2)
pyautogui.press("enter")
pyautogui.write("sie sắp ta mainnet chua ?.", interval = 2)
pyautogui.press("enter")
pyautogui.write("cố lên nào level lâu quá ?.", interval = 2)
pyautogui.press("enter")
pyautogui.write("Ngày ngủ đêm cày air", interval = 2)
pyautogui.press("enter")
pyautogui.write("Mọi người ngủ hết rồi à", interval = 2)
pyautogui.press("enter")
pyautogui.write("E mới vào ạ chào mọi người", interval = 2)
pyautogui.press("enter")
pyautogui.write("chát để lên level mỏi hết tay", interval = 2)
pyautogui.press("enter")
pyautogui.write("lâu lên level 7 quá", interval = 2)
pyautogui.press("enter")
pyautogui.write("Ngày ngủ đêm cày air", interval = 2)
pyautogui.press("enter")
pyautogui.write("Mọi người ngủ hết rồi à", interval = 2)
pyautogui.press("enter")
pyautogui.write("E mới vào ạ chào mọi người", interval = 2)
pyautogui.press("enter")
pyautogui.write("chát để lên level mỏi hết tay", interval = 2)
pyautogui.press("enter")
pyautogui.write("sie sắp ta mainnet chua ?.", interval = 2)
pyautogui.press("enter")
pyautogui.write("cố lên nào level lâu quá ?.", interval = 2)
pyautogui.press("enter")
pyautogui.write("Ngày ngủ đêm cày air", interval = 2)
pyautogui.press("enter")
pyautogui.write("Mọi người ngủ hết rồi à", interval = 2)
pyautogui.press("enter")
pyautogui.write("E mới vào ạ chào mọi người", interval = 2)
pyautogui.press("enter")
pyautogui.write("chát để lên level mỏi hết tay", interval = 2)
pyautogui.press("enter")
pyautogui.write("lâu lên level 7 quá", interval = 2)
pyautogui.press("enter")
pyautogui.write("Ngày ngủ đêm cày air", interval = 2)
pyautogui.press("enter")
pyautogui.write("Mọi người ngủ hết rồi à", interval = 2)
pyautogui.press("enter")
pyautogui.write("E mới vào ạ chào mọi người", interval = 2)
pyautogui.press("enter")
pyautogui.write("chát để lên level mỏi hết tay", interval = 2)
pyautogui.press("enter")
pyautogui.write("sie sắp ta mainnet chua ?.", interval = 2)
pyautogui.press("enter")
pyautogui.write("cố lên nào level lâu quá ?.", interval = 2)
pyautogui.press("enter")
pyautogui.write("Ngày ngủ đêm cày air", interval = 2)
pyautogui.press("enter")
pyautogui.write("Mọi người ngủ hết rồi à", interval = 2)
pyautogui.press("enter")
pyautogui.write("E mới vào ạ chào mọi người", interval = 2)
pyautogui.press("enter")
pyautogui.write("chát để lên level mỏi hết tay", interval = 2)
pyautogui.press("enter")
pyautogui.write("lâu lên level 7 quá", interval = 2)
pyautogui.press("enter")
pyautogui.write("Ngày ngủ đêm cày air", interval = 2)
pyautogui.press("enter")
pyautogui.write("Mọi người ngủ hết rồi à", interval = 2)
pyautogui.press("enter")
pyautogui.write("E mới vào ạ chào mọi người", interval = 2)
pyautogui.press("enter")
pyautogui.write("chát để lên level mỏi hết tay", interval = 2)
pyautogui.press("enter")
pyautogui.write("sie sắp ta mainnet chua ?.", interval = 2)
pyautogui.press("enter")
pyautogui.write("cố lên nào level lâu quá ?.", interval = 2)
pyautogui.press("enter")
pyautogui.write("Ngày ngủ đêm cày air", interval = 2)
pyautogui.press("enter")
pyautogui.write("Mọi người ngủ hết rồi à", interval = 2)
pyautogui.press("enter")
pyautogui.write("E mới vào ạ chào mọi người", interval = 2)
pyautogui.press("enter")
pyautogui.write("chát để lên level mỏi hết tay", interval = 2)
pyautogui.press("enter")
pyautogui.write("lâu lên level 7 quá", interval = 2)
pyautogui.press("enter")
pyautogui.write("Ngày ngủ đêm cày air", interval = 2)
pyautogui.press("enter")
pyautogui.write("Mọi người ngủ hết rồi à", interval = 2)
pyautogui.press("enter")
pyautogui.write("E mới vào ạ chào mọi người", interval = 2)
pyautogui.press("enter")
pyautogui.write("chát để lên level mỏi hết tay", interval = 2)
pyautogui.press("enter")
pyautogui.write("sie sắp ta mainnet chua ?.", interval = 2)
pyautogui.press("enter")
pyautogui.write("cố lên nào level lâu quá ?.", interval = 2)
pyautogui.press("enter")
pyautogui.write("Ngày ngủ đêm cày air", interval = 2)
pyautogui.press("enter")
pyautogui.write("Mọi người ngủ hết rồi à", interval = 2)
pyautogui.press("enter")
pyautogui.write("E mới vào ạ chào mọi người", interval = 2)
pyautogui.press("enter")
pyautogui.write("chát để lên level mỏi hết tay", interval = 2)
pyautogui.press("enter")
pyautogui.write("lâu lên level 7 quá", interval = 2)
pyautogui.press("enter")
pyautogui.write("Ngày ngủ đêm cày air", interval = 2)
pyautogui.press("enter")
pyautogui.write("Mọi người ngủ hết rồi à", interval = 2)
pyautogui.press("enter")
pyautogui.write("E mới vào ạ chào mọi người", interval = 2)
pyautogui.press("enter")
pyautogui.write("chát để lên level mỏi hết tay", interval = 2)
pyautogui.press("enter")
pyautogui.write("sie sắp ta mainnet chua ?.", interval = 2)
pyautogui.press("enter")
pyautogui.write("cố lên nào level lâu quá ?.", interval = 2)
pyautogui.press("enter")
pyautogui.write("Ngày ngủ đêm cày air", interval = 2)
pyautogui.press("enter")
pyautogui.write("Mọi người ngủ hết rồi à", interval = 2)
pyautogui.press("enter")
pyautogui.write("E mới vào ạ chào mọi người", interval = 2)
pyautogui.press("enter")
pyautogui.write("chát để lên level mỏi hết tay", interval = 2)
pyautogui.press("enter")
pyautogui.write("lâu lên level 7 quá", interval = 2)
pyautogui.press("enter")
pyautogui.write("Ngày ngủ đêm cày air", interval = 2)
pyautogui.press("enter")
pyautogui.write("Mọi người ngủ hết rồi à", interval = 2)
pyautogui.press("enter")
pyautogui.write("E mới vào ạ chào mọi người", interval = 2)
pyautogui.press("enter")
pyautogui.write("chát để lên level mỏi hết tay", interval = 2)
pyautogui.press("enter")
pyautogui.write("sie sắp ta mainnet chua ?.", interval = 2)
pyautogui.press("enter")
pyautogui.write("cố lên nào level lâu quá ?.", interval = 2)
pyautogui.press("enter")
pyautogui.write("Ngày ngủ đêm cày air", interval = 2)
pyautogui.press("enter")
pyautogui.write("Mọi người ngủ hết rồi à", interval = 2)
pyautogui.press("enter")
pyautogui.write("E mới vào ạ chào mọi người", interval = 2)
pyautogui.press("enter")
pyautogui.write("chát để lên level mỏi hết tay", interval = 2)
pyautogui.press("enter")
pyautogui.write("lâu lên level 7 quá", interval = 2)
pyautogui.press("enter")
pyautogui.write("Ngày ngủ đêm cày air", interval = 2)
pyautogui.press("enter")
pyautogui.write("Mọi người ngủ hết rồi à", interval = 2)
pyautogui.press("enter")
pyautogui.write("E mới vào ạ chào mọi người", interval = 2)
pyautogui.press("enter")
pyautogui.write("chát để lên level mỏi hết tay", interval = 2)
pyautogui.press("enter")
pyautogui.write("sie sắp ta mainnet chua ?.", interval = 2)
pyautogui.press("enter")
pyautogui.write("cố lên nào level lâu quá ?.", interval = 2)
pyautogui.press("enter")
pyautogui.write("Ngày ngủ đêm cày air", interval = 2)
pyautogui.press("enter")
pyautogui.write("Mọi người ngủ hết rồi à", interval = 2)
pyautogui.press("enter")
pyautogui.write("E mới vào ạ chào mọi người", interval = 2)
pyautogui.press("enter")
pyautogui.write("chát để lên level mỏi hết tay", interval = 2)
pyautogui.press("enter")
pyautogui.write("lâu lên level 7 quá", interval = 2)
pyautogui.press("enter")
pyautogui.write("Ngày ngủ đêm cày air", interval = 2)
pyautogui.press("enter")
pyautogui.write("Mọi người ngủ hết rồi à", interval = 2)
pyautogui.press("enter")
pyautogui.write("E mới vào ạ chào mọi người", interval = 2)
pyautogui.press("enter")
pyautogui.write("chát để lên level mỏi hết tay", interval = 2)
pyautogui.press("enter")
pyautogui.write("sie sắp ta mainnet chua ?.", interval = 2)
pyautogui.press("enter")
pyautogui.write("cố lên nào level lâu quá ?.", interval = 2)
pyautogui.press("enter")
pyautogui.write("Ngày ngủ đêm cày air", interval = 2)
pyautogui.press("enter")
pyautogui.write("Mọi người ngủ hết rồi à", interval = 2)
pyautogui.press("enter")
pyautogui.write("E mới vào ạ chào mọi người", interval = 2)
pyautogui.press("enter")
pyautogui.write("chát để lên level mỏi hết tay", interval = 2)
pyautogui.press("enter")
pyautogui.write("lâu lên level 7 quá", interval = 2)
pyautogui.press("enter")
pyautogui.write("Ngày ngủ đêm cày air", interval = 2)
pyautogui.press("enter")
pyautogui.write("Mọi người ngủ hết rồi à", interval = 2)
pyautogui.press("enter")
pyautogui.write("E mới vào ạ chào mọi người", interval = 2)
pyautogui.press("enter")
pyautogui.write("chát để lên level mỏi hết tay", interval = 2)
pyautogui.press("enter")
pyautogui.write("sie sắp ta mainnet chua ?.", interval = 2)
pyautogui.press("enter")
pyautogui.write("cố lên nào level lâu quá ?.", interval = 2)
pyautogui.press("enter")
pyautogui.write("Ngày ngủ đêm cày air", interval = 2)
pyautogui.press("enter")
pyautogui.write("Mọi người ngủ hết rồi à", interval = 2)
pyautogui.press("enter")
pyautogui.write("E mới vào ạ chào mọi người", interval = 2)
pyautogui.press("enter")
pyautogui.write("chát để lên level mỏi hết tay", interval = 2)
pyautogui.press("enter")
pyautogui.write("lâu lên level 7 quá", interval = 2)
pyautogui.press("enter")
pyautogui.write("Ngày ngủ đêm cày air", interval = 2)
pyautogui.press("enter")
pyautogui.write("Mọi người ngủ hết rồi à", interval = 2)
pyautogui.press("enter")
pyautogui.write("E mới vào ạ chào mọi người", interval = 2)
pyautogui.press("enter")
pyautogui.write("chát để lên level mỏi hết tay", interval = 2)
pyautogui.press("enter")
pyautogui.write("sie sắp ta mainnet chua ?.", interval = 2)
pyautogui.press("enter")
pyautogui.write("cố lên nào level lâu quá ?.", interval = 2)
pyautogui.press("enter")
pyautogui.write("Ngày ngủ đêm cày air", interval = 2)
pyautogui.press("enter")
pyautogui.write("Mọi người ngủ hết rồi à", interval = 2)
pyautogui.press("enter")
pyautogui.write("E mới vào ạ chào mọi người", interval = 2)
pyautogui.press("enter")
pyautogui.write("chát để lên level mỏi hết tay", interval = 2)
pyautogui.press("enter")
pyautogui.write("lâu lên level 7 quá", interval = 2)
pyautogui.press("enter")
pyautogui.write("Ngày ngủ đêm cày air", interval = 2)
pyautogui.press("enter")
pyautogui.write("Mọi người ngủ hết rồi à", interval = 2)
pyautogui.press("enter")
pyautogui.write("E mới vào ạ chào mọi người", interval = 2)
pyautogui.press("enter")
pyautogui.write("chát để lên level mỏi hết tay", interval = 2)
pyautogui.press("enter")
pyautogui.write("sie sắp ta mainnet chua ?.", interval = 2)
pyautogui.press("enter")
pyautogui.write("cố lên nào level lâu quá ?.", interval = 2)
pyautogui.press("enter")
pyautogui.write("Ngày ngủ đêm cày air", interval = 2)
pyautogui.press("enter")
pyautogui.write("Mọi người ngủ hết rồi à", interval = 2)
pyautogui.press("enter")
pyautogui.write("E mới vào ạ chào mọi người", interval = 2)
pyautogui.press("enter")
pyautogui.write("chát để lên level mỏi hết tay", interval = 2)
pyautogui.press("enter")
pyautogui.write("lâu lên level 7 quá", interval = 2)
pyautogui.press("enter")
pyautogui.write("Ngày ngủ đêm cày air", interval = 2)
pyautogui.press("enter")
pyautogui.write("Mọi người ngủ hết rồi à", interval = 2)
pyautogui.press("enter")
pyautogui.write("E mới vào ạ chào mọi người", interval = 2)
pyautogui.press("enter")
pyautogui.write("chát để lên level mỏi hết tay", interval = 2)
pyautogui.press("enter")
pyautogui.write("sie sắp ta mainnet chua ?.", interval = 2)
pyautogui.press("enter")
pyautogui.write("cố lên nào level lâu quá ?.", interval = 2)
pyautogui.press("enter")
pyautogui.write("Ngày ngủ đêm cày air", interval = 2)
pyautogui.press("enter")
pyautogui.write("Mọi người ngủ hết rồi à", interval = 2)
pyautogui.press("enter")
pyautogui.write("E mới vào ạ chào mọi người", interval = 2)
pyautogui.press("enter")
pyautogui.write("chát để lên level mỏi hết tay", interval = 2)
pyautogui.press("enter")
pyautogui.write("lâu lên level 7 quá", interval = 2)
pyautogui.press("enter")
pyautogui.write("Ngày ngủ đêm cày air", interval = 2)
pyautogui.press("enter")
pyautogui.write("Mọi người ngủ hết rồi à", interval = 2)
pyautogui.press("enter")
pyautogui.write("E mới vào ạ chào mọi người", interval = 2)
pyautogui.press("enter")
pyautogui.write("chát để lên level mỏi hết tay", interval = 2)
pyautogui.press("enter")
pyautogui.write("sie sắp ta mainnet chua ?.", interval = 2)
pyautogui.press("enter")
pyautogui.write("cố lên nào level lâu quá ?.", interval = 2)
pyautogui.press("enter")
pyautogui.write("Ngày ngủ đêm cày air", interval = 2)
pyautogui.press("enter")
pyautogui.write("Mọi người ngủ hết rồi à", interval = 2)
pyautogui.press("enter")
pyautogui.write("E mới vào ạ chào mọi người", interval = 2)
pyautogui.press("enter")
pyautogui.write("chát để lên level mỏi hết tay", interval = 2)
pyautogui.press("enter")
pyautogui.write("lâu lên level 7 quá", interval = 2)
pyautogui.press("enter")
pyautogui.write("Ngày ngủ đêm cày air", interval = 2)
pyautogui.press("enter")
pyautogui.write("Mọi người ngủ hết rồi à", interval = 2)
pyautogui.press("enter")
pyautogui.write("E mới vào ạ chào mọi người", interval = 2)
pyautogui.press("enter")
pyautogui.write("chát để lên level mỏi hết tay", interval = 2)
pyautogui.press("enter")
pyautogui.write("sie sắp ta mainnet chua ?.", interval = 2)
pyautogui.press("enter")
pyautogui.write("cố lên nào level lâu quá ?.", interval = 2)
pyautogui.press("enter")
pyautogui.write("Ngày ngủ đêm cày air", interval = 2)
pyautogui.press("enter")
pyautogui.write("Mọi người ngủ hết rồi à", interval = 2)
pyautogui.press("enter")
pyautogui.write("E mới vào ạ chào mọi người", interval = 2)
pyautogui.press("enter")
pyautogui.write("chát để lên level mỏi hết tay", interval = 2)
pyautogui.press("enter")
pyautogui.write("lâu lên level 7 quá", interval = 2)
pyautogui.press("enter")
pyautogui.write("Ngày ngủ đêm cày air", interval = 2)
pyautogui.press("enter")
pyautogui.write("Mọi người ngủ hết rồi à", interval = 2)
pyautogui.press("enter")
pyautogui.write("E mới vào ạ chào mọi người", interval = 2)
pyautogui.press("enter")
pyautogui.write("chát để lên level mỏi hết tay", interval = 2)
pyautogui.press("enter")
pyautogui.write("sie sắp ta mainnet chua ?.", interval = 2)
pyautogui.press("enter")
pyautogui.write("cố lên nào level lâu quá ?.", interval = 2)
pyautogui.press("enter")
pyautogui.write("Ngày ngủ đêm cày air", interval = 2)
pyautogui.press("enter")
pyautogui.write("Mọi người ngủ hết rồi à", interval = 2)
pyautogui.press("enter")
pyautogui.write("E mới vào ạ chào mọi người", interval = 2)
pyautogui.press("enter")
pyautogui.write("chát để lên level mỏi hết tay", interval = 2)
pyautogui.press("enter")
pyautogui.write("lâu lên level 7 quá", interval = 2)
pyautogui.press("enter")
pyautogui.write("Ngày ngủ đêm cày air", interval = 2)
pyautogui.press("enter")
pyautogui.write("Mọi người ngủ hết rồi à", interval = 2)
pyautogui.press("enter")
pyautogui.write("E mới vào ạ chào mọi người", interval = 2)
pyautogui.press("enter")
pyautogui.write("chát để lên level mỏi hết tay", interval = 2)
pyautogui.press("enter")
pyautogui.write("sie sắp ta mainnet chua ?.", interval = 2)
pyautogui.press("enter")
pyautogui.write("cố lên nào level lâu quá ?.", interval = 2)
pyautogui.press("enter")
pyautogui.write("Ngày ngủ đêm cày air", interval = 2)
pyautogui.press("enter")
pyautogui.write("Mọi người ngủ hết rồi à", interval = 2)
pyautogui.press("enter")
pyautogui.write("E mới vào ạ chào mọi người", interval = 2)
pyautogui.press("enter")
pyautogui.write("chát để lên level mỏi hết tay", interval = 2)
pyautogui.press("enter")
pyautogui.write("lâu lên level 7 quá", interval = 2)
pyautogui.press("enter")
pyautogui.write("Ngày ngủ đêm cày air", interval = 2)
pyautogui.press("enter")
pyautogui.write("Mọi người ngủ hết rồi à", interval = 2)
pyautogui.press("enter")
pyautogui.write("E mới vào ạ chào mọi người", interval = 2)
pyautogui.press("enter")
pyautogui.write("chát để lên level mỏi hết tay", interval = 2)
pyautogui.press("enter")
pyautogui.write("sie sắp ta mainnet chua ?.", interval = 2)
pyautogui.press("enter")
pyautogui.write("cố lên nào level lâu quá ?.", interval = 2)
pyautogui.press("enter")
pyautogui.write("Ngày ngủ đêm cày air", interval = 2)
pyautogui.press("enter")
pyautogui.write("Mọi người ngủ hết rồi à", interval = 2)
pyautogui.press("enter")
pyautogui.write("E mới vào ạ chào mọi người", interval = 2)
pyautogui.press("enter")
pyautogui.write("chát để lên level mỏi hết tay", interval = 2)
pyautogui.press("enter")
pyautogui.write("lâu lên level 7 quá", interval = 2)
pyautogui.press("enter")
pyautogui.write("Ngày ngủ đêm cày air", interval = 2)
pyautogui.press("enter")
pyautogui.write("Mọi người ngủ hết rồi à", interval = 2)
pyautogui.press("enter")
pyautogui.write("E mới vào ạ chào mọi người", interval = 2)
pyautogui.press("enter")
pyautogui.write("chát để lên level mỏi hết tay", interval = 2)
pyautogui.press("enter")
pyautogui.write("sie sắp ta mainnet chua ?.", interval = 2)
pyautogui.press("enter")
pyautogui.write("cố lên nào level lâu quá ?.", interval = 2)
pyautogui.press("enter")
pyautogui.write("Ngày ngủ đêm cày air", interval = 2)
pyautogui.press("enter")
pyautogui.write("Mọi người ngủ hết rồi à", interval = 2)
pyautogui.press("enter")
pyautogui.write("E mới vào ạ chào mọi người", interval = 2)
pyautogui.press("enter")
pyautogui.write("chát để lên level mỏi hết tay", interval = 2)
pyautogui.press("enter")
pyautogui.write("lâu lên level 7 quá", interval = 2)
pyautogui.press("enter")
pyautogui.write("Ngày ngủ đêm cày air", interval = 2)
pyautogui.press("enter")
pyautogui.write("Mọi người ngủ hết rồi à", interval = 2)
pyautogui.press("enter")
pyautogui.write("E mới vào ạ chào mọi người", interval = 2)
pyautogui.press("enter")
pyautogui.write("chát để lên level mỏi hết tay", interval = 2)
pyautogui.press("enter")
pyautogui.write("sie sắp ta mainnet chua ?.", interval = 2)
pyautogui.press("enter")
pyautogui.write("cố lên nào level lâu quá ?.", interval = 2)
pyautogui.press("enter")
pyautogui.write("Ngày ngủ đêm cày air", interval = 2)
pyautogui.press("enter")
pyautogui.write("Mọi người ngủ hết rồi à", interval = 2)
pyautogui.press("enter")
pyautogui.write("E mới vào ạ chào mọi người", interval = 2)
pyautogui.press("enter")
pyautogui.write("chát để lên level mỏi hết tay", interval = 2)
pyautogui.press("enter")
pyautogui.write("lâu lên level 7 quá", interval = 2)
pyautogui.press("enter")
pyautogui.write("Ngày ngủ đêm cày air", interval = 2)
pyautogui.press("enter")
pyautogui.write("Mọi người ngủ hết rồi à", interval = 2)
pyautogui.press("enter")
pyautogui.write("E mới vào ạ chào mọi người", interval = 2)
pyautogui.press("enter")
pyautogui.write("chát để lên level mỏi hết tay", interval = 2)
pyautogui.press("enter")
pyautogui.write("sie sắp ta mainnet chua ?.", interval = 2)
pyautogui.press("enter")
pyautogui.write("cố lên nào level lâu quá ?.", interval = 2)
pyautogui.press("enter")
