import pyautogui
import time

time.sleep(2)
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
pyautogui.write("co cay len level nao ! gogogogo", interval = 2)
pyautogui.press("enter")
pyautogui.write("chao ca nha em la thanh vien moi", interval = 2)
pyautogui.press("enter")
pyautogui.write("em tranh cay len cap 7 moi nguoi", interval = 2)
pyautogui.press("enter")
